declare function InventoryItemMiscPasswordPadlockInit(C: Character, item: Item, push: boolean, refresh: boolean): boolean;
declare function InventoryItemMiscPasswordPadlockLoad(): void;
declare function InventoryItemMiscPasswordPadlockDraw(): void;
declare function InventoryItemMiscPasswordPadlockDrawControls(): void;
declare function InventoryItemMiscPasswordPadlockClick(): void;
declare function InventoryItemMiscPasswordPadlockControlsClick(): void;
declare function InventoryItemMiscPasswordPadlockHandleOpenClick(): void;
declare function InventoryItemMiscPasswordPadlockHandleFirstSet(): void;
declare function InventoryItemMiscPasswordPadlockExit(): void;
declare function InventoryItemMiscPasswordPadlockIsSet(): boolean;
declare function InventoryItemMiscPasswordPadlockPublishPasswordChange(C: any): void;
declare const InventoryItemMiscPasswordPadlockPasswordRegex: RegExp;
