// Generated by scripts/speech-baseline.mjs -- lines/conversations the module currently gets wrong.
export const BASELINE_GAP_TEXTS = new Set<string>([
	"Absolutely nobody told me about the party tonight",
	"Chocolate cake is definitely my favourite dessert ever",
	"Everyone seems happy with the decoration choices tonight",
	"I never feel worthless",
	"I'm being such a brat about this",
	"I'm confident enough to ignore all the hate",
	"I'm never going to be useless",
	"I'm not the best at this",
	"I'm not the smartest",
	"I'm your good little pet",
	"I've been bad",
	"I've got nothing to worry about",
	"am I not the prettiest?",
	"aren't I a good girl?",
	"crap",
	"dammit",
	"damn",
	"go to hell",
	"goddamn it",
	"i can do it without fear",
	"im such a dork idk why anyone likes me",
	"that's a cute pussycat",
	"this girl is worthless",
	"what the hell",
	"you can't put me down",
]);
export const BASELINE_GAP_CONVERSATIONS = new Set<string>([

]);
