declare function InventoryItemMiscHighSecurityPadlockInit(C: Character, item: Item, push: boolean, refresh: boolean): boolean;
declare function InventoryItemMiscHighSecurityPadlockLoad(): void;
declare function InventoryItemMiscHighSecurityPadlockPlayerHasKeys(C: any, Item: any): boolean;
declare function InventoryItemMiscHighSecurityPadlockDraw(): void;
declare function InventoryItemMiscHighSecurityPadlockClick(): void;
declare function InventoryItemMiscHighSecurityPadlockExit(): void;
declare var InventoryItemMiscHighSecurityPadlockPlayerCanUnlock: boolean;
declare var HighSecurityPadlockConfigOwner: boolean;
declare var HighSecurityPadlockConfigLover: boolean;
declare var HighSecurityPadlockConfigWhitelist: boolean;
