# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Release LSCG
permissions:
  id-token: write
  pages: write
  contents: write
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    environment: release
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    #- run: npm test

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: dist
        clean-exclude: dev
        git-config-name: github-actions[bot]
        git-config-email: github-actions[bot]@users.noreply.github.com
